sudo: required
language: node_js
cache:
  directories:
  - node_modules
services:
- docker
node_js:
- 9
before_install:
- npm install -g greenkeeper-lockfile@1
install:
- npm i
before_script: greenkeeper-lockfile-update
script: npm test
after_script: greenkeeper-lockfile-upload
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
