sudo: required
language: node_js
cache:
  directories:
  - node_modules
services:
- docker
node_js:
- 8
before_install:
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm test
after_script: greenkeeper-lockfile-upload
deploy:
- provider: script
  script:
    - npm run build
    - docker build .
  on:
    branch: master
