apiVersion: v1
kind: Secret
metadata:
  name: {{ template "budde377-io.fullname" . }}
data:
    serverKey: {{ .Values.secret.serverKey | b64enc | quote }}
    authClientSecret: {{ .Values.secret.authClientSecret | b64enc | quote }}
type: Opaque
