# Default values for budde377-io.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: budde377/budde377-io
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  path: /
  provider:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: budde377@gmail.com
  hosts:
    - budde377.io
  tls:
    - hosts:
        - budde377.io

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


auth:
  redirectUri: https://budde377.io/auth/callback
  clientSecret: ABC

server:
  key: ABC

redis:
  host: redis-redis-cache.redis.svc.cluster.local
