port: 3000

auth:
  domain: budde377-io.eu.auth0.com
  clientId: DmfK7DaWfv1Y23CfIfbwfidpxTBQEwMv
  cleintSecret: FOOBAR
  redirectUri: http://localhost:3000/auth/callback
  responseType: token id_token
  scope: openid email profile

session:
  key: budde377-io-sesh
  rolling: true
  maxAge: 86400000

server:
  keys:
    - foobar
