controller:
  service:
    clusterIP: 10.109.172.166
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
    externalTrafficPolicy: Local
  config:
    hsts: "true"
    hsts-include-subdomains: "false"
    hsts-max-age: "604800"
    hsts-preload: "false"
rbac:
  create: true
